spring:
  datasource:
    url: jdbc:mysql:///myshop
    username: root
    password: wang1998
    driver-class-name: com.mysql.jdbc.Driver

    #配置阿里的数据库连接池，使用的是阿里的druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 60000
  rabbitmq:
    virtual-host: reading
    port: 5672
    username: reading
    password: 123
    host: 192.168.134.128
dubbo:
  application:
    name: service_goods
  registry:
    address: zookeeper://192.168.134.128:2181
  #自动获取没有被占用的端口
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
