spring:
  data:
   solr:
    host: http://192.168.134.128:8080/solr
  rabbitmq:
    host: 192.168.134.128
    port: 5672
    virtual-host: reading
    username: reading
    password: 123
dubbo:
  application:
    name: service_search
  registry:
    address: zookeeper://192.168.134.128:2181
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 60000
  consumer:
    check: false

