server:
  port: 8083
dubbo:
  application:
    name: shop_item
  registry:
    address: zookeeper://192.168.134.128:2181
  consumer:
    check: false
spring:
  rabbitmq:
    host: 192.168.134.128
    port: 5672
    virtual-host: reading
    username: reading
    password: 123
